version: "3"

services:
  web:
    build:
      context: .
      dockerfile: webserver.Dockerfile
    volumes:
      - ./site:/var/www/html
    links:
      - "db:database"
    ports:
      - 7777:80
    depends_on:
      - db
  db:
    image: "mysql:5.6"
    ports:
      - 8888:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mydatabase
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/:ro